nyancodeid/quotes

package-lock.json, quotes/maulayyacyber.yaml
Hi @nyancodeid, please review my pull request 😄 
i have added two quotes from Ali bin Abi Thalib and Abu Hamid Al Ghazali
thanks very much
=> feat(quotes): add quote from Ali bin Abi Thalib & Abu Hamid Al Ghazali

quotes/fariqfgi.yaml
Hi @nyancodeid
I have added a quote from Gus Dur, please review my pull request.
Thanks 👍
=> feat(quotes): add quote from Gus Dur

quotes/faisalindrianto.yaml, src/components/QuoteGallery.vue
Halo! Izin pull request ulang, tadi ada kesalahan dikit. Nyumbang beberapa quotes & saya ada benerin grid untuk viewport md biar lebih keliatan enak. Terima kasih. 😁
=> quotes from faisalindrianto and minor fix

quotes/akrindev.yaml
I'm a big fan of william tanuwijaya. so put some quotes from him to this PR
=> added quotes from william tanuwijaya

quotes/arifai.yaml
Hai mas @nyancodeid, maaf izin PR ulang ya.
=> Add new quotes from Elon Musk

quotes/babaiyu.yaml
=> Add Abraham Lincoln quotes, babaiyu

quotes/fncolon.yaml
Hi, just adding my quotes for this repository.
I hope you liked it!
=> add my quotes for this repository

README.md
fix typo men-*generate*
reformat di-halaman to di halaman
uppercase and lowercase of words
=> minor text improvements

src/components/QuoteCard.vue
=> add hoverable quotes card  #30

src/components/QuoteCard.vue
=> fix hoverable element

package-lock.json, quotes/riyaraa.yaml
Hi @nyancodeid , i added my favorite quote
I hope you like this, Thankyou!
=> added favorite my quote

quotes/raihan71.yaml
=> Add: Some Raihan's Quotes

quotes/myfra.yaml
I have added quotes from Ir. Soekarno & from myself
=> add: quotes

package-lock.json, quotes/ankur12-1610.yaml
Added quote to `/quotes` directory.
=> Added quote to /quotes

quotes/mohsulthana.yaml
Thank you for making this out! Will make another one if I have.
=> Quote by Jalaluddin Rumi added

quotes/irhamshidiq.yaml
Hi @nyancodeid 
I'm currently participating in the hacktoberfest event, could you add label "hacktoberfest-accepted" for me? thanks
=> add quotes for this repository

quotes/fitri.yaml
Hi, here I add quotes by jerome polin. I hope you are acc my pull request with labels "hacktoberfest-accepted" Thank You :)
=> Add Quotes by jerome polin

quotes/Laravel007.yaml
i just romeved yarn lock,and create new PR
=> added quote: quotes

quotes/ayatullahnaufal.yaml
Kata-kata motivasi dari Habib Husein Ja'far
=> Quotes by Habib Husein Ja'far

.env, .gitignore, package-lock.json, package.json, quotes/generator.js, src/components/Dialog.vue, src/components/QuoteCard.vue, src/components/QuoteGallery.vue, src/main.ts, src/types.d.ts, src/utils/helpers.ts, tsconfig.json, vite.config.ts
- Server Side Generator
- Infinite Scroll (with `onscroll` event listener)
- Scale up `<QuoteCard />` on dialog/modal view
- Dialog view on mobile view
- Disable hover effect on mobile view
=> feat: ssg, infinite scroll, and more

quotes/MuhammadNurAshiddiqi.yaml
=> Quotes From Linus Torvalds

quotes/kudaliar032.yaml
Hallo, saya menambahkan sebuah quotes. Thank you
=> Add kudaliar032 quotes

quotes/bryanpratama.yaml
Ini adalah quotes motivasi untuk mereka yang patah semangat
=> added quotes from Jack Ma

quotes/alfaniM.yaml
Add Quote from:
1. - Buzz Lightyear
2. - Thanos
3. - Les Brown
Please acc my pull request :D @nyancodeid
=> Add my quote

quotes/nordeeen.yaml
membuat atau menambahkan dua buah quote islami
=> kontribusi quotes

quotes/generator.js, src/App.vue, src/components/AppHero.vue, src/components/QuoteCard.vue, src/components/QuoteGallery.vue, src/utils/gradients.ts, tailwind.config.js
- Enable dark mode option on `tailwind.config.js`
- Dark Mode theme
- Dark Mode button toggle
=> feat: dark mode

quotes/Ikhari.yaml
Add Quotes by Edith
Please accept my PR
=> Add Quotes by Edith

quotes/riyaraa.yaml
Hi @nyancodeid, Sorry yesterday I added the wrong author, and now I've updated, this my personal mistake, sorry
=> update: Rename Author Quote

src/App.vue, src/components/AppHero.vue
Hi @nyancodeid, I have added 3 theme modes; system theme mode, light mode, and dark mode.
This PR can solve #86
=> Add 3 theme modes

quotes/haikalrr.yml
added quotes about train your mind
=> train your mind

quotes/harisetyopermadi.yml
=> quotes about fishing add

quotes/dyvue.yaml
Hi, just adding quotes for this repository. hope you liked it!
=> Add quotes from dyvue

quotes/agustacandi.yaml
Halo, saya menambahkan satu quote pada file agustacandi.yaml. Mungkin akan saya tambah lagi nanti jika saya menemukan quotes lain yang bagus. Terima kasih!
=> add quote by agustacandi

quotes/hilmizul.yaml
=> hilmizul: december add new quote

quotes/sonic-sabers.yaml
Kindly accept this repo with then label of hacktobertfest-2022
=> hacktoberfest-2022

quotes/anaknyata.yaml
=> Add New Quote

quotes/suryamsj.yaml
Adding quotes from my mom, dad and idols that I always remember to this day
=> Added quotes from my mom, dad and idols

quotes/richardoey.yaml
“In the darkest times, hope is something you give yourself. That is the meaning of inner strength.”
― Uncle Iroh
=> Update richardoey.yml - inner strength - uncle iroh

quotes/sonic-sabers.yaml
I have added a new qoute, Please merge this with the label of hacktoberfest and hacktoberfest2022
=> Added a new Quote

quotes/richardoey.yaml
“Failure is only the opportunity to begin again. Only this time, more wisely.”
=> Update richardoey.yml - Failure - Uncle Iroh
